twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig

    globals:
      categorieRepository: "@App\\Repository\\CategorieRepository"
      cartService: "@App\\Service\\CartService"

when@test:
    twig:
        strict_variables: true
